# Spotify  Playlist Recsys

In [1]:
import json
import pandas as pd
import numpy as np

import boto3
import botocore

In [2]:
s3 = boto3.resource('s3')
# s3.meta.client.head_bucket(Bucket = 'sagemaker-spotifyrecsys')
content_object = s3.Object('sagemaker-spotifyrecsys','mpd.slice.0-999.json')
file_content = content_object.get()['Body'].read().decode('utf-8')
data = json.loads(file_content)

In [16]:
pd.DataFrame(data['playlists']).head().iloc[0]['tracks']

[{u'album_name': u'The Cookbook',
  u'album_uri': u'spotify:album:6vV5UrXcfyQD1wu4Qo2I9K',
  u'artist_name': u'Missy Elliott',
  u'artist_uri': u'spotify:artist:2wIVse2owClT7go1WT98tk',
  u'duration_ms': 226863,
  u'pos': 0,
  u'track_name': u'Lose Control (feat. Ciara & Fat Man Scoop)',
  u'track_uri': u'spotify:track:0UaMYEvWZi0ZqiDOoHU3YI'},
 {u'album_name': u'In The Zone',
  u'album_uri': u'spotify:album:0z7pVBGOD7HCIB7S8eLkLI',
  u'artist_name': u'Britney Spears',
  u'artist_uri': u'spotify:artist:26dSoYclwsYLMAKD3tpOr4',
  u'duration_ms': 198800,
  u'pos': 1,
  u'track_name': u'Toxic',
  u'track_uri': u'spotify:track:6I9VzXrHxO9rA9A5euc8Ak'},
 {u'album_name': u'Dangerously In Love (Alben f\xfcr die Ewigkeit)',
  u'album_uri': u'spotify:album:25hVFAxTlDvXbx2X2QkUkE',
  u'artist_name': u'Beyonc\xe9',
  u'artist_uri': u'spotify:artist:6vWDO969PvNqNYHIOW5v0m',
  u'duration_ms': 235933,
  u'pos': 2,
  u'track_name': u'Crazy In Love',
  u'track_uri': u'spotify:track:0WqIKmW4BTrj3eJFmnC

In [ ]:
playlists = []
track_uris = []
i = -1
while i <= 2000:
    print i
    i+=1
    i_2 = i + 999
    ## Creating correct key
    x = 'mpd.slice.{}-{}.json'.format(i,i_2)
    
    ## Accessing file on s3
    
    content_object = s3.Object('sagemaker-spotifyrecsys',x)
    file_content = content_object.get()['Body'].read().decode('utf-8')
    f = json.loads(file_content)
    
    playlists.extend(f['playlists'])
    
    i+=999

## Spotify Rec Sys Challenge - EDA

In [4]:
## Loading the data

f = json.load(open('./mpd.slice.0-999.json'))

In [6]:
df= pd.DataFrame.from_dict(f['playlists'][:500])

In [7]:
df.iloc[0]['tracks']

[{u'album_name': u'The Cookbook',
  u'album_uri': u'spotify:album:6vV5UrXcfyQD1wu4Qo2I9K',
  u'artist_name': u'Missy Elliott',
  u'artist_uri': u'spotify:artist:2wIVse2owClT7go1WT98tk',
  u'duration_ms': 226863,
  u'pos': 0,
  u'track_name': u'Lose Control (feat. Ciara & Fat Man Scoop)',
  u'track_uri': u'spotify:track:0UaMYEvWZi0ZqiDOoHU3YI'},
 {u'album_name': u'In The Zone',
  u'album_uri': u'spotify:album:0z7pVBGOD7HCIB7S8eLkLI',
  u'artist_name': u'Britney Spears',
  u'artist_uri': u'spotify:artist:26dSoYclwsYLMAKD3tpOr4',
  u'duration_ms': 198800,
  u'pos': 1,
  u'track_name': u'Toxic',
  u'track_uri': u'spotify:track:6I9VzXrHxO9rA9A5euc8Ak'},
 {u'album_name': u'Dangerously In Love (Alben f\xfcr die Ewigkeit)',
  u'album_uri': u'spotify:album:25hVFAxTlDvXbx2X2QkUkE',
  u'artist_name': u'Beyonc\xe9',
  u'artist_uri': u'spotify:artist:6vWDO969PvNqNYHIOW5v0m',
  u'duration_ms': 235933,
  u'pos': 2,
  u'track_name': u'Crazy In Love',
  u'track_uri': u'spotify:track:0WqIKmW4BTrj3eJFmnC

<h3><code>playlists</code> field</h3>
<p>This is an array that typically contains 1,000 playlists. Each playlist is a dictionary that contains the following fields:</p>
<ul>
<li><strong><em>pid</em></strong> - integer - playlist id - the MPD ID of this playlist. This is an integer between 0 and 999,999.</li>
<li class=""><strong><em>name</em></strong> - string - the name of the playlist </li>
<li><strong><em>description</em></strong> - optional string - if present, the description given to the playlist.  Note that user-provided playlist descrptions are a relatively new feature of Spotify, so most playlists do not have descriptions.</li>
<li><strong><em>modified_at</em></strong> - seconds - timestamp (in seconds since the epoch) when this playlist was last updated. Times are rounded to midnight GMT of the date when the playlist was last updated.</li>
<li><strong><em>num_artists</em></strong> - the total number of unique artists for the tracks in the playlist.</li>
<li><strong><em>num_albums</em></strong> - the number of unique albums for the tracks in the playlist</li>
<li><strong><em>num_tracks</em></strong> - the number of tracks in the playlist</li>
<li><strong><em>num_followers</em></strong> - the number of followers this playlist had at the time the MPD was created. (Note that the follower count does not including the playlist creator)</li>
<li><strong><em>num_edits</em></strong> - the number of separate editing sessions. Tracks added in a two hour window are considered to be added in a single editing session.</li>
<li><strong><em>duration_ms</em></strong> - the total duration of all the tracks in the playlist (in milliseconds)</li>
<li><strong><em>collaborative</em></strong> -  boolean - if true, the playlist is a collaborative playlist. Multiple users may contribute tracks to a collaborative playlist.</li>
<li><strong><em>tracks</em></strong> - an array of information about each track in the playlist. Each element in the array is a dictionary with the following fields:

<ul>
<li><strong><em>track_name</em></strong> - the name of the track</li>
<li><strong><em>track_uri</em></strong> - the Spotify URI of the track</li>
<li><strong><em>album_name</em></strong> - the name of the track's album</li>
<li><strong><em>album_uri</em></strong> - the Spotify URI of the album</li>
<li><strong><em>artist_name</em></strong> - the name of the track's primary artist</li>
<li><strong><em>artist_uri</em></strong> - the Spotify URI of track's primary artist</li>
<li><strong><em>duration_ms</em></strong> - the duration of the track in milliseconds</li>
<li><strong><em>pos</em></strong> - the position of the track in the playlist (zero-based)</li>
</ul></li>
</ul>

In [ ]:
## Number of songs over 1,000,000 playlists

# track_uris = []
# i = -1
# while i < 999001:
#     i+=1
#     i_2 = i + 999
#     x = 'mpd.slice.{}-{}.json'.format(i,i_2)
#     f = json.load(open(x))
#     for playlist in f['playlists']:
#         for track in playlist.get('tracks'):
#             track_uris.append(track.get('track_uri').encode('ascii'))
#     i+=999

In [ ]:
# import csv
#
# with open('all_songs','wb') as myfile:
#     wr = csv.writer(myfile, quoting = csv.QUOTE_ALL)
#     wr.writerow(track_uris)

In [5]:
## Finding the number of songs for each of the first 1000 playlists

slice_0_999_pl_len = []
for track in df['tracks'].iloc[:]:
    slice_0_999_pl_len.append(len(track))

In [7]:
print 'mean: ',np.mean(slice_0_999_pl_len)
print 'median: ',np.median(sorted(slice_0_999_pl_len))
print 'min: ',np.min(slice_0_999_pl_len)
print 'max: ',np.max(slice_0_999_pl_len)

mean:  66.83
median:  50.0
min:  5
max:  245


In [8]:
pid = [playlist['pid'] for playlist in  f['playlists'] for track in playlist['tracks']]
track_uri = [track['track_uri'] for playlist in  f['playlists'] for track in playlist['tracks']]

In [9]:
df_2 = pd.DataFrame(data=[pid,track_uri]).T

In [10]:
df_2.columns = ['pid','track_uri']

In [11]:
df_2.head()

pid                             track_uri
0   0  spotify:track:0UaMYEvWZi0ZqiDOoHU3YI
1   0  spotify:track:6I9VzXrHxO9rA9A5euc8Ak
2   0  spotify:track:0WqIKmW4BTrj3eJFmnCKMv
3   0  spotify:track:1AWQoqb9bSvzTjaLralEkT
4   0  spotify:track:1lzr43nnXAijIGYnCT8M8H

In [12]:
occurrance_table = df_2.pivot_table(index=['pid'],columns='track_uri',aggfunc=lambda x: 1.0, fill_value=0)

In [43]:
occurrance_table.T.head()

pid                                   0    1    2    3    4    5    6    7    \
track_uri                                                                      
spotify:track:000mA0etY38nKdvf1N04af    0    0    0    0    0    0    0    0   
spotify:track:000xQL6tZNLJzIrtIgxqSl    0    0    0    0    0    0    0    0   
spotify:track:006AVH7fq061voGXkUiII4    0    0    0    0    0    0    0    0   
spotify:track:006PJvsr6CyV3JdBf7wiNF    0    0    0    0    0    0    0    0   
spotify:track:006yrnQMCZpiUgkR612gC8    0    0    0    0    0    0    0    0   

pid                                   8    9   ...   990  991  992  993  994  \
track_uri                                      ...                             
spotify:track:000mA0etY38nKdvf1N04af    0    0 ...     0    0    0    0    0   
spotify:track:000xQL6tZNLJzIrtIgxqSl    0    0 ...     0    0    0    0    0   
spotify:track:006AVH7fq061voGXkUiII4    0    0 ...     0    0    0    0    0   
spotify:track:006PJvsr6CyV3JdBf7wiNF    0    0 ...     0    0    0    0    0   
spotify:track:006yrnQMCZpiUgkR612gC8    0    0 ...     0    0    0    0    0   

pid                                   995  996  997  998  999  
track_uri                                                      
spotify:track:000mA0etY38nKdvf1N04af    0    0    0    0    0  
spotify:track:000xQL6tZNLJzIrtIgxqSl    0    0    0    0    0  
spotify:track:006AVH7fq061voGXkUiII4    0    0    0    0    1  
spotify:track:006PJvsr6CyV3JdBf7wiNF    0    0    0    0    0  
spotify:track:006yrnQMCZpiUgkR612gC8    0    0    0    0    0  

[5 rows x 1000 columns]

In [13]:
from scipy.sparse import csr_matrix

In [14]:
## condensing sparse matrix
## original numpy dot product causes takes a very long time to run

occurance_matrix = csr_matrix(occurrance_table)

In [15]:
occurance_matrix.toarray().shape

(1000, 34443)

In [16]:
## transposition is so that dot product matrix will be track_uri rows vs track_uri cols
## user is taken out the matrix
## we have the numerator for sim(A,B) calculations

item_subset_occurance = (occurance_matrix.T*occurance_matrix).toarray()

In [17]:
item_subset_occurance

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 4, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [18]:
## total occurance per track

occurance_by_track = np.sum(occurance_matrix,axis=0,dtype=np.float)

In [19]:
occurance_by_track.shape

(1, 34443)

In [20]:
occurance_by_track = occurance_by_track.reshape(34443,1)


In [21]:
occurance_by_track

matrix([[ 1.],
        [ 2.],
        [ 1.],
        ..., 
        [ 4.],
        [ 1.],
        [ 1.]])

In [22]:
## Calculating the denominator for sim(A,B) calculations

item_union_occurance = (occurance_by_track+occurance_by_track.T)-item_subset_occurance

In [24]:
similiarity_matrix = item_subset_occurance/item_union_occurance

In [25]:
similiarity_matrix

matrix([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [26]:
similarity_df = pd.DataFrame(similiarity_matrix,index = occurrance_table.columns, columns = occurrance_table.columns)

In [27]:
similarity_df.head()

track_uri                             spotify:track:000mA0etY38nKdvf1N04af  \
track_uri                                                                    
spotify:track:000mA0etY38nKdvf1N04af                                   1.0   
spotify:track:000xQL6tZNLJzIrtIgxqSl                                   0.0   
spotify:track:006AVH7fq061voGXkUiII4                                   0.0   
spotify:track:006PJvsr6CyV3JdBf7wiNF                                   0.0   
spotify:track:006yrnQMCZpiUgkR612gC8                                   0.0   

track_uri                             spotify:track:000xQL6tZNLJzIrtIgxqSl  \
track_uri                                                                    
spotify:track:000mA0etY38nKdvf1N04af                                   0.0   
spotify:track:000xQL6tZNLJzIrtIgxqSl                                   1.0   
spotify:track:006AVH7fq061voGXkUiII4                                   0.0   
spotify:track:006PJvsr6CyV3JdBf7wiNF                                   0.0   
spotify:track:006yrnQMCZpiUgkR612gC8                                   0.0   

track_uri                             spotify:track:006AVH7fq061voGXkUiII4  \
track_uri                                                                    
spotify:track:000mA0etY38nKdvf1N04af                                   0.0   
spotify:track:000xQL6tZNLJzIrtIgxqSl                                   0.0   
spotify:track:006AVH7fq061voGXkUiII4                                   1.0   
spotify:track:006PJvsr6CyV3JdBf7wiNF                                   0.0   
spotify:track:006yrnQMCZpiUgkR612gC8                                   0.0   

track_uri                             spotify:track:006PJvsr6CyV3JdBf7wiNF  \
track_uri                                                                    
spotify:track:000mA0etY38nKdvf1N04af                                   0.0   
spotify:track:000xQL6tZNLJzIrtIgxqSl                                   0.0   
spotify:track:006AVH7fq061voGXkUiII4                                   0.0   
spotify:track:006PJvsr6CyV3JdBf7wiNF                                   1.0   
spotify:track:006yrnQMCZpiUgkR612gC8                                   0.0   

track_uri                             spotify:track:006yrnQMCZpiUgkR612gC8  \
track_uri                                                                    
spotify:track:000mA0etY38nKdvf1N04af                                   0.0   
spotify:track:000xQL6tZNLJzIrtIgxqSl                                   0.0   
spotify:track:006AVH7fq061voGXkUiII4                                   0.0   
spotify:track:006PJvsr6CyV3JdBf7wiNF                                   0.0   
spotify:track:006yrnQMCZpiUgkR612gC8                                   1.0   

track_uri                             spotify:track:00BuKLSAFkaEkaVAgIMbeA  \
track_uri                                                                    
spotify:track:000mA0etY38nKdvf1N04af                                   0.0   
spotify:track:000xQL6tZNLJzIrtIgxqSl                                   0.0   
spotify:track:006AVH7fq061voGXkUiII4                                   0.0   
spotify:track:006PJvsr6CyV3JdBf7wiNF                                   0.0   
spotify:track:006yrnQMCZpiUgkR612gC8                                   0.0   

track_uri                             spotify:track:00Ci0EXS4fNPnkTbS6wkOh  \
track_uri                                                                    
spotify:track:000mA0etY38nKdvf1N04af                                   0.0   
spotify:track:000xQL6tZNLJzIrtIgxqSl                                   0.0   
spotify:track:006AVH7fq061voGXkUiII4                                   0.0   
spotify:track:006PJvsr6CyV3JdBf7wiNF                                   0.0   
spotify:track:006yrnQMCZpiUgkR612gC8                                   0.0   

track_uri                             spotify:track:00CmjeeHvAVKvx3tcIiZTy  \
track_uri                                                                    
spotify:track:0